### ISSUE TITLE
Switch to Xamarin.Firebase.ML.Vision for Andriod

### ISSUE THREAD

**Issue by themaxsmith** [JimmyPun610/BarcodeScanner.XF#42]
Switch from deprecated Xamarin.GooglePlayServices.Vision to Xamarin.Firebase.ML.Vision on Andriod.

**Comment by themaxsmith** [comment]
provided initial conversation (not working due to firebase setup but it is the correct structure needed) https://github.com/themaxsmith/BarcodeScanner.XF/tree/andriod-switch-to-firebase-ml-kit

**Comment by JimmyPun610** [comment]
Thank you @themaxsmith 

I tried to switch to ML a few months ago but using ML required more settings on the project (just like iOS) so I gave up.
But it would be the future of this project since the original library is deprecated.

I had a quick look at your works which is great. 
Would you complete it and create a pull request or we could work it out together?

**Comment by themaxsmith** [comment]
I will work on it during work hours. I will see if I can finish it up & create a pull request. Just depends on how busy I am at work.

**Comment by drmikesell** [comment]
Not sure that the Xamarin.GooglePlayServices.Vision package is deprecated, since it's showing up as recently updated, and a newer pre-release version is also available.

**Comment by JimmyPun610** [comment]
> Not sure that the Xamarin.GooglePlayServices.Vision package is deprecated, since it's showing up as recently updated, and a newer pre-release version is also available.

Yes. And the updated package of mine is using v119 now.

**Comment by pulmuone** [comment]
Xamarin.Android CameraX + Scan Barcodes with ML Kit on Android

**Comment by JimmyPun610** [comment]
6.0.0-pre is applied MLKit and CameraX in Android
