### ISSUE TITLE
Additional Dependencies for Xamarin.Forms iOS

### ISSUE THREAD

**Issue by SelaineW** [JimmyPun610/BarcodeScanner.XF#63]
I needed to add three more NuGet packages to build without error for this line:

_ = Firebase.RemoteConfig.RemoteConfig.SharedInstance; // missing using statement for "RemoteConfig".

Added to the iOS project to resolve error:
Xamarin.Firebase.iOS.Core
Xamarin.Firebase.iOS.MLKit
Xamarin.Firebase.iOS.MLKit.Common

**Comment by brunonocetti** [comment]
Try adding `Xamarin.Firebase.iOS.RemoteConfig` package instead. 
Adding those packages (actually just adding `Xamarin.Firebase.iOS.MLKit`) fixes your problem because it has this other package (`Xamarin.Firebase.iOS.RemoteConfig`) as a dependency

**Comment by brunonocetti** [comment]
@JimmyPun610 it would be a good idea to add this to the docs. The sample app works because it has as dependency all of this Firebase packages. But maybe other project don't use this packages directly and need to add Xamarin.Firebase.iOS.RemoteConfig as dependency.

And we must remember that this line is necessary because of a linker problem, maybe there's a better way to avoid the linker breaking the app.

**Comment by JimmyPun610** [comment]
Hi there,

As a fix of #50, I just updated the version to 5.0.5.
After changing the referencing libraries to Xamarin.Firebase.iOS.MLKit.Vision and Xamarin.Firebase.iOS.Core only, seems that line is no longer needed.

Also, I clear the sample app reference and install the latest package from nuget to simulate a new project.

**Comment by SelaineW** [comment]
5.0.5 does resolve the issue!  Closing.
Thanks!!!
