### ISSUE TITLE
Enhancement: QR-/Barcode- generator?

### ISSUE THREAD

**Issue by ramonB1996** [JimmyPun610/BarcodeScanner.XF#68]
Hi @JimmyPun610,

I really like this library and it works alot better than the current alternative (`ZXing`) in my opinion. 

My idea might be out-of-scope for this project, as it is called a BarcodeSCANNER, but I will give it a try.

It would be great if there would be a generator for QR-codes (and maybe barcodes) like the `ZXing` library already has.
This way I could fully remove `Zxing` and only use one Barcode library.

Please tell me your opinion for this idea.

**Comment by JimmyPun610** [comment]
Hi @ramonB1996 

Thank you for your suggestion, but I am not planning to do the generation part at this moment because MLKit is not supporting that. I would suggest you pick QRCoder. 
https://github.com/codebude/QRCoder

I guess it supports Xamarin, here is what I found
https://github.com/iamlawrencev/QRCodeGenerator-Xamarin.Forms

**Comment by ramonB1996** [comment]
Hi @JimmyPun610,

Thank you for the links and suggestion. I can understand your point and will close this :)
